author:
  name: Tim Alexander Teige
  email: tim.teige91@gmail.com
title: Blog about everything and nothing, but mostly application development
description: >-
  Yet another blog about coding, development and lessons learned.
baseurl: ""
url: ""
#twitter_username:
github_username:  tteige
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
markdown: kramdown
